bmnc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import bmnc_berita.urls as berita
import bmnc_core.urls as home
import app_profile.urls as profile
import app_melihat_daftar_berita.urls as lihat_daftar_berita
import app_melihat_polling_biasa.urls as lihat_polling_biasa
import bmnc_polling.urls as polling
import accounts.urls as account
from bmnc import views

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='home/', permanent=True), name='root'),
    url(r'home/', include(home, namespace='home')),
    url(r'daftar_berita/', include(lihat_daftar_berita, namespace='lihat_daftar_berita')),
    url(r'daftar_polling_biasa/', include(lihat_polling_biasa, namespace='lihat_polling_biasa')),
    url(r'profile/', include(profile, namespace='profile')),
    url(r'berita/', include(berita, namespace='berita')),
    # url(r'^$', RedirectView.as_view(url='home/', permanent=True), name='root'),
    # url(r'home/', include(home, namespace='home')),
    url(r'^account/', include(account, namespace='login page')),
    url(r'^polling/', include(polling, namespace='polling')),
]

bmnc_berita/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView
from .views import index, list_berita, create_berita, add_berita

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^list/$', list_berita, name='list-berita'),

    # Tambah berita
    url(r'^new/$', create_berita, name="create-berita"),
    url(r'^add-berita', add_berita, name="add-berita"),
]

bmnc_core/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name="index"),
]

bmnc_polling/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView
from .views import index, create_polling_biasa, create_polling_berita, add_polling_biasa ,add_polling_berita

urlpatterns = [
    url(r'^$', index, name="index"),

    # Tambah polling

    ## Tambah polling biasa
    url(r'^biasa/new/$', create_polling_biasa, name="create-polling-biasa"),
    url(r'^biasa/add-polling', add_polling_biasa, name="add-polling-biasa"),

    ## Tambah polling berita
    url(r'^berita/new/$', create_polling_berita, name="create-polling-berita"),
    url(r'^berita/add-polling', add_polling_berita, name="add-polling-berita"),
]

templates/partials/footer.html
<!-- partials/footer.html -->
<div class = "footer" align="center"><p id="footer">&copy; Kelompok 11 Basis Data - B 2017/2018</p></div>

templates/partials/header.html
{% load static %}
<!-- partials/header.html -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">
            <img src="{% static 'img/bmnc_logo.png' %}" alt="" style="height: 50px;width: auto;margin: 0%">
        </a>
    
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile:index' %}">Profile</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Berita
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'berita:create-berita' %}">Tambah Berita</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Polling
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'polling:create-polling-biasa' %}">Tambah Polling</a>
                        <a class="dropdown-item" href="{% url 'polling:create-polling-berita' %}">Tambah Polling Berita</a>
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Register</button>
            </form>
        </div>
>>>>>>> templates/partials/header.html
    </div>
</nav>