app_profile/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

bmnc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import bmnc_berita.urls as berita
import bmnc_core.urls as home
import app_profile.urls as profile
import app_melihat_daftar_berita.urls as lihat_daftar_berita
import app_melihat_polling_biasa.urls as lihat_polling_biasa
import bmnc_polling.urls as polling
import accounts.urls as account
from bmnc import views

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='home/', permanent=True), name='root'),
    url(r'home/', include(home, namespace='home')),
    url(r'daftar_berita/', include(lihat_daftar_berita, namespace='lihat_daftar_berita')),
    url(r'daftar_polling_biasa/', include(lihat_polling_biasa, namespace='lihat_polling_biasa')),
    url(r'profile/', include(profile, namespace='profile')),
    url(r'berita/', include(berita, namespace='berita')),
    # url(r'^$', RedirectView.as_view(url='home/', permanent=True), name='root'),
    # url(r'home/', include(home, namespace='home')),
    url(r'^account/', include(account, namespace='login page')),
    url(r'^polling/', include(polling, namespace='polling')),
]

app_profile/models.py
from django.db import models

# Create your models here.

app_profile/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
# Create your views here.

response = {}
def index(request):
	response['author'] = "Muhammad Sulthan Rafi" #TODO Implement yourname
	html = 'profile.html'
	return render(request, html, response)

app_profile/templates/profile.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}
    Profile
{% endblock %}

{% block style %}
    <!-- insert static/css here -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'css/stail.css' %}" type="text/css"> </head>
{% endblock %}

{% block staticfiles %}
    <!-- insert static files here -->
{% endblock %}

{% block content %}
  <body>
  <div class="mx-auto w-75 h-50">
    <div class="section">
      <div class="row">
        <div class="col-md-12"> </div>
      </div>
    </div>
    <div class="container mx-auto">
      <div class="row">
        <div class="col-md-12"> </div>
      </div>
      <div class="row">
        <div class="col-md-3 mx-auto px-2 col-xl-5">
          <h1 class="text-center">
            <b class="text-dark text-center">PROFILE</b>
          </h1>
        </div>
      </div>
      <div class="row bg-light">
        <div class="col-md-4">
          <img class="d-block rounded p-2 m-3" src="http://blogdailyherald.com/wp-content/uploads/2014/10/wallpaper-for-facebook-profile-photo.jpg" style="height: 200px; width: 250px"> </div>
        <div class="col-md-8">
          <h1 class="mx-auto py-3 text-left">Muhammad Imron</h1>
          <div class="row h-25 bg-light">
            <div class="col-md-12">
              <p class="">E - Mail: yandex@imron.com
                <br>
                <br>Jumlah Berita: -</p>
              <a href="{% url 'lihat_daftar_berita:index' %}">Daftar Berita</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block javascript %}
    <!-- insert script here -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% endblock %}


</html>