bmnc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import bmnc_berita.urls as berita
import bmnc_core.urls as home
import app_profile.urls as profile
import app_melihat_daftar_berita.urls as lihat_daftar_berita
import app_melihat_polling_biasa.urls as lihat_polling_biasa
import bmnc_polling.urls as polling
import accounts.urls as account
from bmnc import views

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='home/', permanent=True), name='root'),
    url(r'home/', include(home, namespace='home')),
    url(r'daftar_berita/', include(lihat_daftar_berita, namespace='lihat_daftar_berita')),
    url(r'daftar_polling_biasa/', include(lihat_polling_biasa, namespace='lihat_polling_biasa')),
    url(r'profile/', include(profile, namespace='profile')),
    url(r'berita/', include(berita, namespace='berita')),
    # url(r'^$', RedirectView.as_view(url='home/', permanent=True), name='root'),
    # url(r'home/', include(home, namespace='home')),
    url(r'^account/', include(account, namespace='login page')),
    url(r'^polling/', include(polling, namespace='polling')),
]

bmnc_polling/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView
from .views import index, create_polling_biasa, create_polling_berita, add_polling_biasa ,add_polling_berita

urlpatterns = [
    url(r'^$', index, name="index"),

    # Tambah polling

    ## Tambah polling biasa
    url(r'^biasa/new/$', create_polling_biasa, name="create-polling-biasa"),
    url(r'^biasa/add-polling', add_polling_biasa, name="add-polling-biasa"),

    ## Tambah polling berita
    url(r'^berita/new/$', create_polling_berita, name="create-polling-berita"),
    url(r'^berita/add-polling', add_polling_berita, name="add-polling-berita"),
]

bmnc_core/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class Berita(models.Model):
    url = models.CharField(primary_key=True, max_length=50)
    judul = models.CharField(max_length=100)
    topik = models.CharField(max_length=100)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    jumlah_kata = models.IntegerField()
    rarata_rating = models.FloatField()
    id_universitas = models.ForeignKey('Universitas', models.DO_NOTHING, db_column='id_universitas')

    class Meta:
        managed = False
        db_table = 'berita'


class Dosen(models.Model):
    id_narasumber = models.ForeignKey('Narasumber', models.DO_NOTHING, db_column='id_narasumber', primary_key=True)
    nik_dosen = models.CharField(max_length=20)
    jurusan = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'dosen'


class Honor(models.Model):
    id_narasumber = models.IntegerField(primary_key=True)
    tgl_diberikan = models.DateTimeField()
    jumlah_berita = models.IntegerField()
    jumlah_gaji = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'honor'
        unique_together = (('id_narasumber', 'tgl_diberikan'),)


class Komentar(models.Model):
    id = models.IntegerField(primary_key=True)
    tanggal = models.DateTimeField()
    jam = models.TimeField()
    konten = models.CharField(max_length=100)
    nama_user = models.CharField(max_length=50)
    email_user = models.CharField(max_length=50)
    url_user = models.CharField(max_length=50)
    url_berita = models.ForeignKey(Berita, models.DO_NOTHING, db_column='url_berita')

    class Meta:
        managed = False
        db_table = 'komentar'


class Kupon(models.Model):
    id = models.IntegerField(primary_key=True)
    tgl_diberikan = models.DateTimeField()
    tgl_kadaluarsa = models.DateTimeField()
    id_narasumber = models.ForeignKey('Narasumber', models.DO_NOTHING, db_column='id_narasumber')

    class Meta:
        managed = False
        db_table = 'kupon'


class Mahasiswa(models.Model):
    id_narasumber = models.ForeignKey('Narasumber', models.DO_NOTHING, db_column='id_narasumber', primary_key=True)
    npm = models.CharField(max_length=20)
    jurusan = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'mahasiswa'


class Narasumber(models.Model):
    id = models.IntegerField(primary_key=True)
    nama = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    tempat = models.CharField(max_length=50)
    tanggal = models.DateTimeField()
    no_hp = models.CharField(max_length=50)
    jumlah_berita = models.IntegerField()
    rerata_kata = models.IntegerField()
    id_universitas = models.ForeignKey('Universitas', models.DO_NOTHING, db_column='id_universitas')

    class Meta:
        managed = False
        db_table = 'narasumber'


class NarasumberBerita(models.Model):
    url_berita = models.ForeignKey(Berita, models.DO_NOTHING, db_column='url_berita')
    id_narasumber = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'narasumber_berita'


class Polling(models.Model):
    id = models.IntegerField(primary_key=True)
    polling_start = models.DateTimeField()
    polling_end = models.DateTimeField()
    total_responden = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'polling'


class PollingBerita(models.Model):
    id_polling = models.ForeignKey(Polling, models.DO_NOTHING, db_column='id_polling', primary_key=True)
    url_berita = models.ForeignKey(Berita, models.DO_NOTHING, db_column='url_berita', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'polling_berita'


class PollingBiasa(models.Model):
    id_polling = models.ForeignKey(Polling, models.DO_NOTHING, db_column='id_polling', primary_key=True)
    url = models.CharField(max_length=50)
    deskripsi = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'polling_biasa'


class Rating(models.Model):
    url_berita = models.ForeignKey(Berita, models.DO_NOTHING, db_column='url_berita', primary_key=True)
    ip_address = models.CharField(max_length=50)
    nilai = models.FloatField()

    class Meta:
        managed = False
        db_table = 'rating'
        unique_together = (('url_berita', 'ip_address'),)


class Rekening(models.Model):
    nomor = models.CharField(primary_key=True, max_length=20)
    nama_bank = models.CharField(max_length=20)
    id_narasumber = models.ForeignKey(Narasumber, models.DO_NOTHING, db_column='id_narasumber')

    class Meta:
        managed = False
        db_table = 'rekening'


class Respon(models.Model):
    id_polling = models.ForeignKey(Polling, models.DO_NOTHING, db_column='id_polling', primary_key=True)
    jawaban = models.CharField(max_length=50)
    jumlah_dipilih = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'respon'
        unique_together = (('id_polling', 'jawaban'),)


class Responden(models.Model):
    id_polling = models.ForeignKey(Polling, models.DO_NOTHING, db_column='id_polling', primary_key=True)
    ip_address = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'responden'
        unique_together = (('id_polling', 'ip_address'),)


class Riwayat(models.Model):
    url_berita = models.ForeignKey(Berita, models.DO_NOTHING, db_column='url_berita', primary_key=True)
    id_riwayat = models.IntegerField()
    waktu_revisi = models.DateTimeField()
    konten = models.TextField()

    class Meta:
        managed = False
        db_table = 'riwayat'
        unique_together = (('url_berita', 'id_riwayat'),)


class Staf(models.Model):
    id_narasumber = models.ForeignKey(Narasumber, models.DO_NOTHING, db_column='id_narasumber', primary_key=True)
    nik_staf = models.CharField(max_length=20)
    jurusan = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'staf'


class Tag(models.Model):
    url_berita = models.ForeignKey(Berita, models.DO_NOTHING, db_column='url_berita', primary_key=True)
    tag = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'tag'
        unique_together = (('url_berita', 'tag'),)


class Universitas(models.Model):
    id = models.IntegerField(primary_key=True)
    jalan = models.CharField(max_length=50)
    kelurahan = models.CharField(max_length=50)
    provinsi = models.CharField(max_length=50)
    kodepos = models.CharField(max_length=10)
    website = models.CharField(max_length=50)

    def __str__ (self):
        return '<Universitas %d>' % self.id

    class Meta:
        managed = False
        db_table = 'universitas'

bmnc_polling/models.py
from django.db import models

# Create your models here.

bmnc_polling/forms.py
from django.forms import ModelForm, widgets
from bmnc_core.models import Polling, PollingBiasa, PollingBerita

class PollingBiasaForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(PollingBiasaForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if field.widget.__class__ == widgets.TextInput:
                if 'class' in field.widget.attrs:
                    field.widget.attrs['class'] += 'form-control'
                else:
                    field.widget.attrs.update({'class':'form-control'})
    
    class Meta:
        model = PollingBiasa
        fields = ['url', 'deskripsi']

class PollingBeritaForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(PollingBeritaForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if field.widget.__class__ == widgets.TextInput:
                if 'class' in field.widget.attrs:
                    field.widget.attrs['class'] += 'form-control'
                else:
                    field.widget.attrs.update({'class':'form-control'})
    
    class Meta:
        model = PollingBerita
        fields = ['url_berita']

bmnc_polling/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseBadRequest
from django.db import connection
from django.views.decorators.csrf import csrf_exempt

from bmnc_core.models import Berita, Polling, PollingBerita, PollingBiasa, Respon
from bmnc_berita.forms import BeritaForm
from .forms import PollingBiasaForm, PollingBeritaForm

import datetime

response = {}

# Create your views here.
def index(request):
    return render(request, 'landing_page.html', response)

def create_polling_biasa(request):
    response['polling_biasa_form'] = PollingBiasaForm
    return render(request, 'tambah_polling_biasa.html', response)

@csrf_exempt
def add_polling_biasa(request):
    return None

def create_polling_berita(request):
    response['polling_berita_form'] = PollingBeritaForm
    return render(request, 'tambah_polling_berita.html', response)

@csrf_exempt
def add_polling_berita(request):
    return None

bmnc_polling/templates/tambah_polling_berita.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}Tambah Polling Biasa{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_polling.css' %}" />
{% endblock %}

{% block staticfiles %}
    <!-- insert static files here -->
{% endblock %}

{% block content %}
    <section name="form-tambah-polling" id="input-list">
        <h2 class="my-list-title">Tambah Polling</h2>
        <div class="container">
            <div>
                <form id="form" method="POST" action="{% url 'polling:add-polling-berita' %}">
                    {% csrf_token %}
                    {{ polling_berita_form }}
                    <tr><th><label for="id_polling_start">
                        Polling start:
                    </label></th><td>
                    <input type="datetime-local" name="polling_start" class="form-control" required id="id_polling_start" /></td></tr>
                    <tr><th><label for="id_polling_end">
                        Polling end:
                    </label></th><td>
                    <input type="datetime-local" name="polling_end" class="form-control" required id="id_polling_end" /></td></tr>
                    <div align="center" id="add_polling">
                        <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
                    </div>
                    <br>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

{% block javascript %}
    <!-- insert script here -->
{% endblock %}

bmnc_polling/templates/tambah_polling_biasa.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}Tambah Polling Biasa{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_polling.css' %}" />
{% endblock %}

{% block staticfiles %}
    <!-- insert static files here -->
{% endblock %}

{% block content %}
    <section name="form-tambah-polling" id="input-list">
        <h2 class="my-list-title">Tambah Polling</h2>
        <div class="container">
            <div>
                <form id="form" method="POST" action="{% url 'polling:add-polling-biasa' %}">
                    {% csrf_token %}
                    {{ polling_biasa_form }}
                    <tr><th><label for="id_polling_start">
                        Polling start:
                    </label></th><td>
                    <input type="datetime-local" name="polling_start" class="form-control" required id="id_polling_start" /></td></tr>
                    <tr><th><label for="id_polling_end">
                        Polling end:
                    </label></th><td>
                    <input type="datetime-local" name="polling_end" class="form-control" required id="id_polling_end" /></td></tr>
                    <div align="center" id="add_polling">
                        <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
                    </div>
                    <br>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

{% block javascript %}
    <!-- insert script here -->
{% endblock %}