bmnc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import bmnc_berita.urls as berita
import bmnc_core.urls as home
import app_profile.urls as profile
import app_melihat_daftar_berita.urls as lihat_daftar_berita
import app_melihat_polling_biasa.urls as lihat_polling_biasa
import bmnc_polling.urls as polling
import accounts.urls as account
from bmnc import views

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='home/', permanent=True), name='root'),
    url(r'home/', include(home, namespace='home')),
    url(r'daftar_berita/', include(lihat_daftar_berita, namespace='lihat_daftar_berita')),
    url(r'daftar_polling_biasa/', include(lihat_polling_biasa, namespace='lihat_polling_biasa')),
    url(r'profile/', include(profile, namespace='profile')),
    url(r'berita/', include(berita, namespace='berita')),
    # url(r'^$', RedirectView.as_view(url='home/', permanent=True), name='root'),
    # url(r'home/', include(home, namespace='home')),
    url(r'^account/', include(account, namespace='login page')),
    url(r'^polling/', include(polling, namespace='polling')),
]

bmnc_berita/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView
from .views import index, list_berita, create_berita, add_berita

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^list/$', list_berita, name='list-berita'),

    # Tambah berita
    url(r'^new/$', create_berita, name="create-berita"),
    url(r'^add-berita', add_berita, name="add-berita"),
]

bmnc_berita/models.py
from django.db import models

# Create your models here.

bmnc_berita/forms.py
from django.forms import ModelForm, widgets
from bmnc_core.models import Berita

class BeritaForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(BeritaForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if field.widget.__class__ == widgets.TextInput:
                if 'class' in field.widget.attrs:
                    field.widget.attrs['class'] += 'form-control'
                else:
                    field.widget.attrs.update({'class':'form-control'})
            elif field.widget.__class__ == widgets.Select:
                if 'class' in field.widget.attrs:
                    field.widget.attrs['class'] += 'form-control'
                else:
                    field.widget.attrs.update({'class':'form-control'})

    class Meta:
        model = Berita
        fields = ['url', 'judul', 'topik', 'id_universitas']

bmnc_berita/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseBadRequest
from django.db import connection
from django.views.decorators.csrf import csrf_exempt

from bmnc_core.models import Berita, Universitas
from .forms import BeritaForm

import datetime

response = {}

# Create your views here.
def index(request):
    return render(request, 'landing_page.html', response)

def list_berita(request):
    return render(request, 'landing_page.html', response)

def create_berita(request):
    response['news_form'] = BeritaForm
    return render(request, 'tambah_berita.html', response)

@csrf_exempt
def add_berita(request):
    form = BeritaForm(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        url = request.POST['url']
        judul = request.POST['judul']
        topik = request.POST['topik']
        date = str(datetime.datetime.now())
        created_at = date
        updated_at = date
        id_universitas = request.POST['id_universitas']

        query = "INSERT INTO BERITA VALUES ('" + url + "','" + judul + "', '" + topik + "', '" \
                + created_at + "', '" + updated_at + "', " + "0" + ", " + "0" + ", " + id_universitas + ")"
        with connection.cursor() as c:
            c.execute(query)
        return HttpResponseRedirect('/berita/new/')
    return HttpResponseBadRequest()

bmnc_berita/templates/tambah_berita.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}Tambah Berita{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_berita.css' %}" />
{% endblock %}

{% block staticfiles %}
    <!-- insert static files here -->
{% endblock %}

{% block content %}
    <section name="form-tambah-berita" id="input-list">
        <h2 class="my-list-title">Tambah Berita</h2>
        <div class="container">
            <div>
                <form id="form" method="POST" action="{% url 'berita:add-berita' %}">
                    {% csrf_token %}
                    {{ news_form }}
                    <div align="center" id="add_berita">
                        <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
                    </div>
                    <br>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

{% block javascript %}
    <!-- insert script here -->
{% endblock %}